[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
command = "parcel build src/index.html --public-url /"
publish = "dist"

[build.environment]
NODE_VERSION = "16.19.0"

[build.processing]
skip_processing = true